(()=>{
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const $=id=>document.getElementById(id);
const esc=v=>{const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML};
const dateOnly=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'')?v:'';
const formatDate=v=>new Date(v+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const todayISO=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
let events=[],rangeStart=todayISO(),rangeEnd=todayISO(),initialised=false;
function getSavedDays(){try{const x=JSON.parse(localStorage.getItem('bw_interest_days')||'null');return Array.isArray(x)&&x.length?new Set(x.map(Number)):new Set([0,1,2,3,4,5,6])}catch{return new Set([0,1,2,3,4,5,6])}}
function applyDays(){const s=getSavedDays();document.querySelectorAll('[data-bw-day]').forEach(x=>x.checked=s.has(Number(x.dataset.bwDay)))}
async function loadEvents(){const r=await fetch('./events.json?searchdata='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Could not load events');const j=await r.json();events=Array.isArray(j)?j:(Array.isArray(j.events)?j.events:[]);return events}
function enabledVenue(e){try{const saved=JSON.parse(localStorage.getItem('bw_venues')||'null');return !Array.isArray(saved)||e.venue==='Other'||saved.includes(e.venue)}catch{return true}}
function isComedy(e){const h=[e.category,e.type,e.genre,e.tags,e.title,e.description].filter(Boolean).join(' ').toLowerCase();return /\b(comedy|comedian|stand.?up|standup|improv|improvisation|sketch|open mic comedy)\b/.test(h)}
function card(e){return `<article class="bw-range-card"><div class="bw-range-date">${e.date?formatDate(e.date):'Date TBC'}</div><div class="bw-range-title">${esc(e.title||'Untitled event')}</div><div class="bw-range-meta">${esc(e.venue||'Venue TBC')}${e.time?' · '+esc(e.time):''}${e.finish_time?'–'+esc(e.finish_time):''}</div>${e.price?`<div class="bw-range-price">${esc(e.price)}</div>`:''}${e.ticket_url?`<a class="bw-range-ticket" href="${esc(e.ticket_url)}" target="_blank" rel="noopener">TICKETS ↗</a>`:''}</article>`}
function currentComedy(){return !$('comedyTab')?.classList.contains('hidden')}
function renderRange(){const box=$('bwRangeResults');if(!box)return;const comedy=currentComedy();const rows=events.filter(e=>dateOnly(e.date)&&e.date>=rangeStart&&e.date<=rangeEnd&&enabledVenue(e)&&(!comedy||isComedy(e))).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.time||'').localeCompare(b.time||''));box.innerHTML=`<div class="bw-range-head"><h2>${comedy?'Comedy':'Discover'}</h2><div class="note">${formatDate(rangeStart)}${rangeStart!==rangeEnd?' – '+formatDate(rangeEnd):''} · ${rows.length} event${rows.length===1?'':'s'}</div></div>`+(rows.length?rows.map(card).join(''):'<div class="empty">No events found in this date range for your selected venues.</div>');box.classList.remove('hidden');$('bwSearchResults')?.classList.add('hidden');$('discover')?.classList.toggle('hidden',comedy);$('comedyTab')?.classList.toggle('hidden',!comedy);if(comedy)$('comedyList')?.classList.add('hidden')}
function showNormal(){$('bwRangeResults')?.classList.add('hidden');$('bwSearchResults')?.classList.add('hidden');const active=document.querySelector('.nav button.active')?.dataset.tab||'discover';['discover','comedyTab','peopleTab','venuesTab'].forEach(id=>$(id)?.classList.toggle('hidden',id!==active));if(active==='comedyTab')$('comedyList')?.classList.remove('hidden')}
async function search(){const input=$('bwActSearch'),box=$('bwSearchResults');if(!input||!box)return;const q=(input.value||'').trim().toLocaleLowerCase();if(!q){showNormal();return}box.classList.remove('hidden');$('bwRangeResults')?.classList.add('hidden');['discover','comedyTab'].forEach(id=>$(id)?.classList.add('hidden'));box.innerHTML='<h2>Act search</h2><div class="note">Searching every date in the event catalogue.</div><div class="empty">Searching…</div>';try{await loadEvents();const rows=events.filter(e=>[e.title,e.description,e.venue,e.category,e.type,e.genre,e.tags].some(v=>String(v||'').toLocaleLowerCase().includes(q))).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.time||'').localeCompare(b.time||''));box.innerHTML=`<h2>Act search</h2><div class="note">${rows.length} result${rows.length===1?'':'s'} · date window does not limit act search</div>`+(rows.length?rows.map(card).join(''):'<div class="empty">No matching acts found.</div>')}catch(err){console.error(err);box.innerHTML='<h2>Act search</h2><div class="empty">Could not load the event catalogue. Please refresh and try again.</div>'}}
function setDates(from,to){rangeStart=from;rangeEnd=to;const f=$('bwDateFrom'),t=$('bwDateTo'),b=$('bwDateButton');if(f)f.value=from;if(t)t.value=to;if(b)b.textContent=from===to?'Date: '+formatDate(from):'Dates: '+formatDate(from)+' – '+formatDate(to)}
function applyRange(){const from=$('bwDateFrom')?.value,to=$('bwDateTo')?.value,pop=$('bwDatePop');if(!dateOnly(from)||!dateOnly(to)||from>to){alert('Please choose a valid From and To date.');return}setDates(from,to);pop?.classList.remove('open');loadEvents().then(renderRange).catch(err=>{console.error(err);alert('Could not load events. Please refresh and try again.')})}
function setup(){if(initialised)return;if(!$('bwActSearchButton')||!$('bwDateButton'))return;initialised=true;const searchBtn=$('bwActSearchButton'),searchBox=$('bwActSearch'),dateBtn=$('bwDateButton'),pop=$('bwDatePop');const from=$('bwDateFrom'),to=$('bwDateTo');setDates(todayISO(),todayISO());searchBtn.onclick=search;searchBox?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search()}});dateBtn.onclick=()=>pop?.classList.toggle('open');$('bwThisWeek')?.addEventListener('click',()=>{const d=new Date(),day=(d.getDay()+6)%7;d.setHours(12,0,0,0);d.setDate(d.getDate()-day);const end=new Date(d);end.setDate(end.getDate()+6);setDates(d.toISOString().slice(0,10),end.toISOString().slice(0,10))});$('bwApplyDates')?.addEventListener('click',applyRange);document.addEventListener('click',e=>{const nav=e.target.closest?.('.nav button');if(nav&&$('bwRangeResults')&&!$('bwRangeResults').classList.contains('hidden'))setTimeout(renderRange,0)});applyDays()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
new MutationObserver(setup).observe(document.documentElement,{childList:true,subtree:true});
})();