(()=>{
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const $=id=>document.getElementById(id);
const esc=v=>{const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML};
const dateOnly=v=>/^\d{4}-\d{2}-\d{2}$/.test(v||'')?v:'';
const formatDate=v=>new Date(v+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const todayISO=()=>{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
let events=[];
let rangeStart=todayISO(),rangeEnd=todayISO();
function getSavedDays(){try{const x=JSON.parse(localStorage.getItem('bw_interest_days')||'null');return Array.isArray(x)&&x.length?new Set(x.map(Number)):new Set([0,1,2,3,4,5,6])}catch{return new Set([0,1,2,3,4,5,6])}}
function applyDays(){const s=getSavedDays();document.querySelectorAll('[data-bw-day]').forEach(x=>x.checked=s.has(Number(x.dataset.bwDay)));document.querySelectorAll('.day').forEach(el=>{const m=el.textContent.match(/^(MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY|SUNDAY)/);if(!m)return;const i=DAYS.indexOf(m[1].charAt(0)+m[1].slice(1).toLowerCase());el.style.display=s.has(i)?'':'none';let n=el.nextElementSibling;while(n&&!n.classList.contains('day')){n.style.display=s.has(i)?'':'none';n=n.nextElementSibling}})}
async function loadEvents(){const r=await fetch('./events.json?searchdata='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Could not load events');const j=await r.json();events=Array.isArray(j)?j:(Array.isArray(j.events)?j.events:[]);return events}
function enabledVenue(e){try{const saved=JSON.parse(localStorage.getItem('bw_venues')||'null');if(!Array.isArray(saved))return true;return e.venue==='Other'||saved.includes(e.venue)}catch{return true}}
function isComedy(e){const h=[e.category,e.type,e.genre,e.tags,e.title,e.description].filter(Boolean).join(' ').toLowerCase();return /\b(comedy|comedian|stand.?up|standup|improv|improvisation|sketch|open mic comedy)\b/.test(h)}
function card(e){return `<article class="bw-range-card"><div class="bw-range-date">${e.date?formatDate(e.date):'Date TBC'}</div><div class="bw-range-title">${esc(e.title||'Untitled event')}</div><div class="bw-range-meta">${esc(e.venue||'Venue TBC')}${e.time?' · '+esc(e.time):''}${e.finish_time?'–'+esc(e.finish_time):''}</div>${e.price?`<div class="bw-range-price">${esc(e.price)}</div>`:''}${e.ticket_url?`<a class="bw-range-ticket" href="${esc(e.ticket_url)}" target="_blank" rel="noopener">TICKETS ↗</a>`:''}</article>`}
function renderRange(){const box=$('bwRangeResults');if(!box)return;const start=rangeStart,end=rangeEnd;const comedy=$('comedyTab')?.classList.contains('hidden')===false;const rows=events.filter(e=>dateOnly(e.date)&&e.date>=start&&e.date<=end&&enabledVenue(e)&&(!comedy||isComedy(e))).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.time||'').localeCompare(b.time||''));box.innerHTML=`<div class="bw-range-head"><h2>${comedy?'Comedy':'Discover'}</h2><div class="note">${formatDate(start)}${start!==end?' – '+formatDate(end):''} · ${rows.length} event${rows.length===1?'':'s'}</div></div>`+(rows.length?rows.map(card).join(''):'<div class="empty">No events found in this date range for your selected venues.</div>');box.classList.remove('hidden');$('discover')?.classList.add('hidden');if(comedy){$('comedyTab')?.classList.remove('hidden');$('comedyList')?.classList.add('hidden')}else{$('comedyTab')?.classList.add('hidden')}}
function showNormal(){const b=$('bwRangeResults');b?.classList.add('hidden');$('discover')?.classList.remove('hidden');$('comedyTab')?.classList.add('hidden');$('comedyList')?.classList.remove('hidden')}
async function search(){const input=$('bwActSearch'),box=$('bwSearchResults');const q=(input?.value||'').trim().toLocaleLowerCase();if(!q){box?.classList.add('hidden');showNormal();return}box.classList.remove('hidden');$('discover')?.classList.add('hidden');$('comedyTab')?.classList.add('hidden');box.innerHTML='<h2>Act search</h2><div class="note">Searching every date in the event catalogue.</div><div class="empty">Searching…</div>';try{await loadEvents();const rows=events.filter(e=>[e.title,e.description,e.venue,e.category,e.type,e.genre,e.tags].some(v=>String(v||'').toLocaleLowerCase().includes(q))).sort((a,b)=>(a.date||'').localeCompare(b.date||'')||(a.time||'').localeCompare(b.time||''));box.innerHTML=`<h2>Act search</h2><div class="note">${rows.length} result${rows.length===1?'':'s'} · date window does not limit act search</div>`+(rows.length?rows.map(card).join(''):'<div class="empty">No matching acts found.</div>')}catch(e){console.error(e);box.innerHTML='<h2>Act search</h2><div class="empty">Could not load the event catalogue. Please refresh and try again.</div>'}}
function setDates(from,to){rangeStart=from;rangeEnd=to;const f=$('bwDateFrom'),t=$('bwDateTo'),b=$('bwDateButton');if(f)f.value=from;if(t)t.value=to;if(b)b.textContent=from===to?'Date: '+formatDate(from):'Dates: '+formatDate(from)+' – '+formatDate(to)}
function setup(){
 const searchBox=$('bwActSearch'),searchBtn=$('bwActSearchButton');if(searchBox&&searchBtn){searchBtn.addEventListener('click',search);searchBox.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();search()}})}
 const db=$('bwDateButton'),pop=$('bwDatePop'),from=$('bwDateFrom'),to=$('bwDateTo');if(db&&pop&&from&&to){const d=new Date();const iso=todayISO();setDates(iso,iso);db.addEventListener('click',()=>pop.classList.toggle('open'));$('bwThisWeek')?.addEventListener('click',()=>{const d=new Date();const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);const a=d.toISOString().slice(0,10);const e=new Date(d);e.setDate(e.getDate()+6);setDates(a,e.toISOString().slice(0,10))});$('bwApplyDates')?.addEventListener('click',()=>{if(!dateOnly(from.value)||!dateOnly(to.value)||from.value>to.value){alert('Please choose a valid From and To date.');return}setDates(from.value,to.value);pop.classList.remove('open');loadEvents().then(renderRange).catch(()=>alert('Could not load events. Please refresh and try again.'))})}
 const grid=$('bwDayGrid');if(grid){grid.querySelectorAll('[data-bw-day]').forEach(c=>{c.checked=getSavedDays().has(Number(c.dataset.bwDay));c.addEventListener('change',()=>{const vals=[...grid.querySelectorAll('[data-bw-day]:checked')].map(x=>Number(x.dataset.bwDay));localStorage.setItem('bw_interest_days',JSON.stringify(vals.length?vals:[0,1,2,3,4,5,6]));applyDays()})});applyDays()}
 const nav=document.querySelectorAll('.nav button');nav.forEach(b=>b.addEventListener('click',()=>{if(b.dataset.tab==='discover'&&rangeStart&&rangeEnd&&$('bwRangeResults')&&!$('bwRangeResults').classList.contains('hidden'))renderRange();else if(b.dataset.tab==='comedyTab'&&$('bwRangeResults')&&!$('bwRangeResults').classList.contains('hidden'))renderRange()}));
}
window.addEventListener('load',()=>setTimeout(setup,250));
})();