const CACHE="brighton-weekend-v91-assets";
const CORE=["./","./index.html","./manifest.webmanifest","./favicon.ico","./icons/icon-32.png","./icons/icon-192.png","./icons/icon-512.png","./icons/icon-192-maskable.png","./icons/icon-512-maskable.png","./icons/apple-touch-icon.png","./about.html","./privacy.html","./terms.html","./profile-icons/brown-bear.svg","./profile-icons/red-panda-bear.svg","./profile-icons/giant-panda-bear.svg","./profile-icons/moose.jpg","./profile-icons/orange-tabby.jpg","./profile-icons/black-cat.jpg","./profile-icons/fluffy-cat.jpg","./profile-icons/tuxedo-cat.jpg"];
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
async function transformIndex(response){
 const html=await response.text();
 const css=`<style id="bw-tools-css">
.bw-tools{display:grid;grid-template-columns:minmax(150px,.8fr) minmax(180px,1.5fr) auto;gap:8px;margin-top:10px}.bw-tools button,.bw-tools input{min-height:42px;padding:9px 12px;border:1px solid #294657;border-radius:12px;background:#102536;color:#F3E4C9;font:600 .78rem var(--font-ui);box-sizing:border-box}.bw-tools input::placeholder{color:#8194a0}.bw-search-button{cursor:pointer;background:#FF7767!important;color:#08141F!important;border-color:#FF7767!important}.bw-date-pop{display:none;margin-top:8px;padding:12px;border:1px solid #294657;border-radius:14px;background:#102536}.bw-date-pop.open{display:block}.bw-date-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.bw-date-row label{font-size:.7rem;color:#A7B5BE}.bw-date-row input{margin-top:4px;width:100%}.bw-date-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.bw-date-actions button{width:auto;cursor:pointer}.bw-search-results,.bw-range-results{max-width:860px;margin:0 auto;padding:10px 15px 120px}.bw-search-results h2,.bw-range-results h2{margin:12px 0 4px}.bw-range-card{background:#102536;border:1px solid #294657;border-radius:16px;padding:14px;margin:9px 0}.bw-range-date{color:#8FE0D5;font-weight:800;font-size:.76rem}.bw-range-title{font-size:1rem;font-weight:800;margin:3px 0}.bw-range-meta{color:#A7B5BE;font-size:.75rem}.bw-range-price{margin-top:5px}.bw-range-ticket{display:inline-block;margin-top:9px;padding:7px 10px;border-radius:9px;background:#FF7767;color:#08141F;text-decoration:none;font-size:.7rem;font-weight:800}@media(max-width:600px){.bw-tools{grid-template-columns:1fr 1fr}.bw-search-button{grid-column:1 / -1}}
</style>`;
 const dayCss=`<style id="bw-day-settings">.day-preferences{margin-top:14px;padding-top:14px;border-top:1px solid #294657}.day-preferences h4{margin:0 0 5px;font-size:.9rem}.day-preferences .note{margin-bottom:10px}.day-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.day-choice{display:flex;align-items:center;gap:8px;padding:10px 11px;border:1px solid #294657;border-radius:12px;background:#0F2231;color:#F3E4C9;font-size:.78rem;font-weight:600}.day-choice input{accent-color:#4DB6AC;width:18px;height:18px}.day-choice input:checked+span{color:#8FE0D5}@media(min-width:520px){.day-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}</style>`;
 const dayHtml='<div class="day-preferences"><h4>Days</h4><div class="note">Choose which days you want to see in Discover and Comedy.</div><div id="bwDayGrid" class="day-grid">'+['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=>`<label class="day-choice"><input type="checkbox" data-bw-day="${i}" checked><span>${d}</span></label>`).join('')+'</div></div>';
 const tools='<div class="bw-tools"><button id="bwDateButton" type="button">Date window</button><input id="bwActSearch" type="search" placeholder="Search acts… e.g. Ben Folds Five" autocomplete="off"><button id="bwActSearchButton" class="bw-search-button" type="button">Search</button></div><div id="bwDatePop" class="bw-date-pop"><div class="bw-date-row"><label>From<input id="bwDateFrom" type="date"></label><label>To<input id="bwDateTo" type="date"></label></div><div class="bw-date-actions"><button type="button" id="bwThisWeek">This week</button><button type="button" id="bwApplyDates">Apply date range</button></div></div>';
 let patched=html.replace('</head>',dayCss+css+'</head>');
 patched=patched.replace("const start=getThursday(), end=new Date(friday);end.setDate(end.getDate()+2);", "const start=new Date(friday);start.setDate(start.getDate()-4); const end=new Date(start);end.setDate(end.getDate()+6);");
 patched=patched.replace("const start=getThursday(), end=new Date(start);end.setDate(end.getDate()+3);", "const start=new Date(friday);start.setDate(start.getDate()-4); const end=new Date(start);end.setDate(end.getDate()+6);");
 patched=patched.replace("['THURSDAY','FRIDAY','SATURDAY','SUNDAY']", "['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']");
 patched=patched.replace('<div id="venueList"></div></div>','<div id="venueList"></div>'+dayHtml+'</div>');
 patched=patched.replace('</header>',tools+'</div></header>');
 patched=patched.replace('</header><main id="discover"','</header><section id="bwSearchResults" class="bw-search-results hidden"></section><section id="bwRangeResults" class="bw-range-results hidden"></section><main id="discover"');
 patched=patched.replace('</body>','<script src="./search-tools.js"></script></body>');
 return new Response(patched,{status:response.status,statusText:response.statusText,headers:response.headers});
}
self.addEventListener("fetch",event=>{const req=event.request;if(req.method!=="GET")return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith("events.json")){event.respondWith(fetch(req,{cache:"no-store"}).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put(req,c));return r}).catch(()=>caches.match(req)));return}if(req.mode==="navigate"||url.pathname.endsWith('.html')){event.respondWith(fetch(req,{cache:'no-store'}).then(async r=>{const transformed=(url.pathname.endsWith('/index.html')||url.pathname.endsWith('/'))?await transformIndex(r):r;const c=transformed.clone();caches.open(CACHE).then(x=>x.put(req,c));return transformed}).catch(()=>caches.match(req).then(r=>r||caches.match('./index.html'))));return}event.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put(req,c));return r})))});