const CACHE="brighton-weekend-v89-assets";
const CORE=["./","./index.html","./manifest.webmanifest","./favicon.ico","./icons/icon-32.png","./icons/icon-192.png","./icons/icon-512.png","./icons/icon-192-maskable.png","./icons/icon-512-maskable.png","./icons/apple-touch-icon.png","./about.html","./privacy.html","./terms.html","./profile-icons/brown-bear.svg","./profile-icons/red-panda-bear.svg","./profile-icons/giant-panda-bear.svg","./profile-icons/moose.jpg","./profile-icons/orange-tabby.jpg","./profile-icons/black-cat.jpg","./profile-icons/fluffy-cat.jpg","./profile-icons/tuxedo-cat.jpg"];
self.addEventListener("install",e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting())));
self.addEventListener("activate",e=>e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
async function transformIndex(response){
 const html=await response.text();
 const css='<style id="bw-search-date">.bw-tools{display:grid;grid-template-columns:1fr 1.6fr;gap:8px;margin-top:10px}.bw-tools button,.bw-tools input{width:100%;min-height:42px;padding:9px 12px;border:1px solid #294657;border-radius:12px;background:#102536;color:#F3E4C9;font:600 .78rem var(--font-ui)}.bw-tools input::placeholder{color:#8194a0}.bw-date-pop{display:none;margin-top:8px;padding:12px;border:1px solid #294657;border-radius:14px;background:#102536}.bw-date-pop.open{display:block}.bw-date-row{display:grid;grid-template-columns:1fr 1fr;gap:8px}.bw-date-row label{font-size:.7rem;color:#A7B5BE}.bw-date-row input{margin-top:4px}.bw-date-actions{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.bw-date-actions button{width:auto;padding:8px 11px}.bw-search-results{max-width:860px;margin:0 auto;padding:10px 15px 120px}.bw-search-results h2{margin:12px 0 4px}.bw-search-results .note{margin-bottom:12px}.bw-search-card{background:#102536;border:1px solid #294657;border-radius:16px;padding:14px;margin:9px 0}.bw-search-card .date{color:#8FE0D5;font-weight:800;font-size:.76rem}.bw-search-card .title{font-size:1rem;font-weight:800;margin:3px 0}.bw-search-card .meta{color:#A7B5BE;font-size:.75rem}.bw-search-card a{display:inline-block;margin-top:9px;padding:7px 10px;border-radius:9px;background:#FF7767;color:#08141F;text-decoration:none;font-size:.7rem;font-weight:800}.bw-search-status{color:#A7B5BE;font-size:.75rem;padding:10px 0}@media(max-width:520px){.bw-tools{grid-template-columns:1fr 1fr}}</style>';
 const dayCss='<style id="bw-day-settings">.day-preferences{margin-top:14px;padding-top:14px;border-top:1px solid #294657}.day-preferences h4{margin:0 0 5px;font-size:.9rem}.day-preferences .note{margin-bottom:10px}.day-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.day-choice{display:flex;align-items:center;gap:8px;padding:10px 11px;border:1px solid #294657;border-radius:12px;background:#0F2231;color:#F3E4C9;font-size:.78rem;font-weight:600}.day-choice input{accent-color:#4DB6AC;width:18px;height:18px}.day-choice input:checked+span{color:#8FE0D5}@media(min-width:520px){.day-grid{grid-template-columns:repeat(4,minmax(0,1fr))}}</style>';
 const dayHtml='<div class="day-preferences"><h4>Days</h4><div class="note">Choose which days you want to see in Discover and Comedy.</div><div id="bwDayGrid" class="day-grid">'+['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((d,i)=>`<label class="day-choice"><input type="checkbox" data-bw-day="${i}" checked><span>${d}</span></label>`).join('')+'</div></div>';
 const tools='<div class="bw-tools"><button id="bwDateButton" type="button">Date window</button><input id="bwActSearch" type="search" placeholder="Search acts… e.g. Ben Folds Five" autocomplete="off"></div><div id="bwDatePop" class="bw-date-pop"><div class="bw-date-row"><label>From<input id="bwDateFrom" type="date"></label><label>To<input id="bwDateTo" type="date"></label></div><div class="bw-date-actions"><button type="button" id="bwThisWeek">This week</button><button type="button" id="bwApplyDates">Apply</button></div></div>';
 const code=`<script>(function(){
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],dayKey='bw_interest_days';
const $=id=>document.getElementById(id);
function selected(){try{const x=JSON.parse(localStorage.getItem(dayKey)||'null');return Array.isArray(x)&&x.length?new Set(x.map(Number)):new Set([0,1,2,3,4,5,6])}catch(e){return new Set([0,1,2,3,4,5,6])}}
function applyDays(){const s=selected();document.querySelectorAll('[data-bw-day]').forEach(c=>c.checked=s.has(Number(c.dataset.bwDay)));document.querySelectorAll('.day').forEach(el=>{const m=el.textContent.match(/^(MONDAY|TUESDAY|WEDNESDAY|THURSDAY|FRIDAY|SATURDAY|SUNDAY)/);if(!m)return;const idx=DAYS.indexOf(m[1].charAt(0)+m[1].slice(1).toLowerCase()),show=s.has(idx);el.style.display=show?'':'none';let n=el.nextElementSibling;while(n&&!n.classList.contains('day')){n.style.display=show?'':'none';n=n.nextElementSibling}})}
function monday(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x}
function iso(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function fmtDate(d){return d.toLocaleDateString('en-GB',{day:'numeric',month:'short'})}
function setWeek(start){const today=$('today'),prev=$('prev'),next=$('next');if(!today||!prev||!next)return;today.click();const base=monday(new Date()),target=monday(start);let weeks=Math.round((target-base)/604800000);const step=weeks>0?next:prev;for(let i=0;i<Math.abs(weeks);i++)step.click()}
function renderDateWindow(start){const end=new Date(start);end.setDate(end.getDate()+6);const from=$('bwDateFrom'),to=$('bwDateTo'),btn=$('bwDateButton');if(from)from.value=iso(start);if(to)to.value=iso(end);if(btn)btn.textContent='Dates: '+fmtDate(start)+' – '+fmtDate(end);setWeek(start)}
function escapeHtml(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}
async function search(q){const box=$('bwSearchResults');if(!box)return;if(!q){box.classList.add('hidden');$('discover')?.classList.remove('hidden');$('comedyTab')?.classList.remove('hidden');return}box.classList.remove('hidden');$('discover')?.classList.add('hidden');$('comedyTab')?.classList.add('hidden');box.innerHTML='<h2>Act search</h2><div class="note">Searching all dates in the event catalogue.</div><div class="bw-search-status">Searching…</div>';try{const r=await fetch('./events.json?actsearch='+encodeURIComponent(q)+'&t='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('events.json '+r.status);const j=await r.json();const list=Array.isArray(j)?j:(Array.isArray(j.events)?j.events:[]);const needle=q.toLocaleLowerCase();const rows=list.filter(e=>[e.title,e.description,e.venue,e.category].some(v=>String(v||'').toLocaleLowerCase().includes(needle))).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.time||'').localeCompare(String(b.time||'')));box.innerHTML='<h2>Act search</h2><div class="note">'+rows.length+' result'+(rows.length===1?'':'s')+' · date window does not limit act search</div>'+(rows.length?rows.map(e=>'<article class="bw-search-card"><div class="date">'+(e.date?new Date(e.date+'T12:00:00').toLocaleDateString('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'Date TBC')+'</div><div class="title">'+escapeHtml(e.title||'Untitled event')+'</div><div class="meta">'+escapeHtml(e.venue||'Venue TBC')+(e.time?' · '+escapeHtml(e.time):'')+'</div>'+(e.ticket_url?'<a href="'+escapeHtml(e.ticket_url)+'" target="_blank" rel="noopener">TICKETS ↗</a>':'')+'</article>').join(''):'<div class="empty">No matching acts found.</div>')}catch(e){console.error('Brighton Weekend act search failed',e);box.innerHTML='<h2>Act search</h2><div class="empty">Could not load the event catalogue. Please refresh and try again.</div>'}}
function setup(){
 const grid=$('bwDayGrid');if(grid){grid.querySelectorAll('[data-bw-day]').forEach(c=>{c.checked=selected().has(Number(c.dataset.bwDay));c.addEventListener('change',()=>{const vals=[...grid.querySelectorAll('[data-bw-day]:checked')].map(x=>Number(x.dataset.bwDay));localStorage.setItem(dayKey,JSON.stringify(vals.length?vals:[0,1,2,3,4,5,6]));applyDays()})});applyDays()}
 const d=$('bwDateButton'),pop=$('bwDatePop'),from=$('bwDateFrom'),to=$('bwDateTo'),searchBox=$('bwActSearch');if(!d||!pop||!from||!to||!searchBox)return;
 let start=monday(new Date());renderDateWindow(start);
 d.addEventListener('click',e=>{e.preventDefault();pop.classList.toggle('open')});
 $('bwThisWeek').addEventListener('click',e=>{e.preventDefault();start=monday(new Date());renderDateWindow(start);pop.classList.remove('open')});
 $('bwApplyDates').addEventListener('click',e=>{e.preventDefault();if(!from.value||!to.value||from.value>to.value){alert('Choose a valid date window.');return}const chosen=monday(new Date(from.value+'T12:00:00'));start=chosen;renderDateWindow(start);pop.classList.remove('open')});
 let timer;searchBox.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(searchBox.value.trim()),250)});
 searchBox.addEventListener('search',()=>search(searchBox.value.trim()));
}
window.addEventListener('load',()=>setTimeout(setup,150));
})();</script>`;
 let patched=html.replace('</head>',dayCss+css+'</head>');
 patched=patched.replace("const start=getThursday(), end=new Date(friday);end.setDate(end.getDate()+2);", "const start=new Date(friday);start.setDate(start.getDate()-4); const end=new Date(start);end.setDate(end.getDate()+6);");
 patched=patched.replace("const start=getThursday(), end=new Date(start);end.setDate(end.getDate()+3);", "const start=new Date(friday);start.setDate(start.getDate()-4); const end=new Date(start);end.setDate(end.getDate()+6);");
 patched=patched.replace("['THURSDAY','FRIDAY','SATURDAY','SUNDAY']", "['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY']");
 patched=patched.replace('<div id="venueList"></div></div>','<div id="venueList"></div>'+dayHtml+'</div>');
 patched=patched.replace('</header>',tools+'</div></header>');
 patched=patched.replace('</header><main id="discover"','</header><section id="bwSearchResults" class="bw-search-results hidden"></section><main id="discover"');
 patched=patched.replace('</body>',code+'</body>');
 return new Response(patched,{status:response.status,statusText:response.statusText,headers:response.headers});
}
self.addEventListener("fetch",event=>{const req=event.request;if(req.method!=="GET")return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(url.pathname.endsWith("events.json")){event.respondWith(fetch(req,{cache:"no-store"}).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put(req,c));return r}).catch(()=>caches.match(req)));return}if(req.mode==="navigate"||url.pathname.endsWith('.html')){event.respondWith(fetch(req,{cache:'no-store'}).then(async r=>{const transformed=(url.pathname.endsWith('/index.html')||url.pathname.endsWith('/'))?await transformIndex(r):r;const c=transformed.clone();caches.open(CACHE).then(x=>x.put(req,c));return transformed}).catch(()=>caches.match(req).then(r=>r||caches.match('./index.html'))));return}event.respondWith(caches.match(req).then(cached=>cached||fetch(req).then(r=>{const c=r.clone();caches.open(CACHE).then(x=>x.put(req,c));return r})))});